# Generated by Django 5.2.9 on 2025-12-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_clothes_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.ImageField(default='default.png', upload_to='website/static/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='model_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type_of_clothes',
            field=models.CharField(max_length=50),
        ),
    ]
