# Generated by Django 5.2.9 on 2025-12-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_clothes_image_alter_clothes_model_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='model_name',
            new_name='name',
        ),
    ]
