# Generated by Django 5.2.9 on 2025-12-08 20:08

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_model_name_clothes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(default='default.png', upload_to=website.models.clothes_upload_path),
        ),
    ]
